apiVersion: skaffold/v2beta8
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
# Do not push to dockerhub whenever an image is built
build:
  local:
    push: false
    useBuildkit: true
  # googleCloudBuild:
  #   projectId: <Found in Project details in google cloud>
  artifacts:
    # Auth Service
    - image: gagandeep39/ticket-booking-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # Tickets service
    - image: gagandeep39/ticket-booking-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # Orders Service
    - image: gagandeep39/ticket-booking-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # Frontend code
    - image: gagandeep39/ticket-booking-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    # Frontend code
    - image: gagandeep39/ticket-booking-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gagandeep39/ticket-booking-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
