apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: gagandeep39/ticket-booking-auth
          resources:
            limits:
              memory: '200Mi'
              cpu: '350m'
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongo-srv:27017/auth
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                    key: JWT_KEY
                    name: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth-srv-clusterip-port
      protocol: TCP
      port: 3000
      targetPort: 3000
