apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: gagandeep39/ticket-booking-expiration
          # resources:
          #   limits:
          #     memory: '200Mi'
          #     cpu: '300m'
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              # Can be any name
              value: ticketing
            - name: NATS_CLIENT_ID
              # Provides deployment name to client id environement
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
