# kubectl create secret generic jwt-secret --from-literal=JWT_KEY=lonely
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # 'lonely' Encoded using base64
  JWT_KEY: bG9uZWx5 
