apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: gagandeep39/ticket-booking-payments
          # resources:
          #   limits:
          #     memory: '200Mi'
          #     cpu: '300m'
          env:
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              # Can be any name
              value: ticketing
            - name: NATS_CLIENT_ID
              # Provides deployment name to client id environement
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: STRIPE_SECRET_KEY
                  name: stripe-secret

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments-srv-clusterip-port
      protocol: TCP
      port: 3000
      targetPort: 3000
