apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  # 'lonely' Encoded using base64
  STRIPE_SECRET_KEY: sk_test_51I3zWOI8py6Rj5ufAOC0uwcqJy64pIGVg5OK9O80NqICeXosLJYYlDKESNeD0NRTudoL6MtF6u7n6e9tjseDGnZW00JkeuTLoT
