name: Docker Push - Payments microservice

on:
  push:
    branches:
      - '**'
    paths:
      - 'payments/**'
defaults:
  run:
    working-directory: payments

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "NOW=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
        # Required for Build and push step
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # Required for Build and push step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Required for Build and push step
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: payments
          file: payments/Dockerfile
          push: true
          tags: |
            gagandeep39/ticket-booking-payments:${{env.NOW}}
            gagandeep39/ticket-booking-payments:latest
